artifacts_root: artifacts

data_ingestion:
   root_dir: artifacts/data_ingestion
   source: "C:/Users/91787/Programming/Projects/Sentiment-Analysis_Roberta/data/Reviews.zip"
   local_data_file: "C:/Users/91787/Programming/Projects/Sentiment-Analysis_Roberta/data/Reviews.zip"
   unzip_dir: "artifacts/data_ingestion"


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["Reviews.csv"]



model_trainer:
   root_dir: artifacts/model_trainer
   data_path: artifacts/data_ingestion/Reviews.csv
   model_ckpt: cardiffnlp/twitter-roberta-base-sentiment
   model_save: artifacts/model_trainer/pepegasus-samsum-model/model.safetensors
   tokenizer_save: artifacts/model_trainer/tokenizer
